# Generated by Django 5.2.1 on 2025-06-01 17:56

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_redirect'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. Agriculture, Élevage', max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Post Category',
                'verbose_name_plural': 'Post Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(help_text='Publication date of the article', verbose_name='Post date')),
                ('intro', models.CharField(help_text='Brief introduction displayed in post listings', max_length=250)),
                ('body', wagtail.fields.RichTextField(help_text='Main content of the post')),
                ('featured', models.BooleanField(default=False, help_text='Display this post in featured sections', verbose_name='Featured Post')),
                ('image', models.ForeignKey(blank=True, help_text='Main image for the post (1200x600px recommended)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select categories for this post', to='blog.categories', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-date'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
