# Generated by Django 5.2.1 on 2025-06-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A short title or heading for this promotion', max_length=255)),
                ('link_url', models.URLField(blank=True, help_text='(Optional) where this promotion should point')),
                ('link_text', models.CharField(blank=True, help_text='(Optional) text for the link button (e.g. “Learn More”)', max_length=255)),
                ('image', models.ForeignKey(help_text='Upload the promotional image', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Seasonal Promotion',
                'verbose_name_plural': 'Seasonal Promotions',
            },
        ),
    ]
